[package]
name = "rapier-issue-287"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rapier3d = "0.12.0-alpha.1"
rapier_testbed3d = "0.12.0-alpha.1"
